
package gui;

import javax.swing.JOptionPane;
import model.Cell;

/**
 *
 * @author Marian Luca/ phantomCat1
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        jAlgoPanel.setVisible(false);
        gridPanel = jMainPanel;
        jMainPanel.invalidate();
        repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTopPanel = new javax.swing.JPanel();
        jSolveButton = new javax.swing.JButton();
        jSliderLabel = new javax.swing.JLabel();
        jSpeedSlider = new javax.swing.JSlider();
        jHelpButton = new javax.swing.JButton();
        jStopButton = new javax.swing.JButton();
        jEraserRadioButton = new javax.swing.JRadioButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jAlgoPanel = new java.awt.Panel();
        jDijkstraButton = new javax.swing.JButton();
        jAStarButton = new javax.swing.JButton();
        jDFSButton = new javax.swing.JButton();
        jBFSButton = new javax.swing.JButton();
        jGreedyButton = new javax.swing.JButton();
        jBidirectionalButton = new javax.swing.JButton();
        jMainPanel = new gui.GridPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(860, 640));
        setResizable(false);

        jTopPanel.setPreferredSize(new java.awt.Dimension(860, 70));

        jSolveButton.setText("Solve");
        jSolveButton.setFocusable(false);
        jSolveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSolveButtonMouseClicked(evt);
            }
        });

        jSliderLabel.setText("Speed:");

        jSpeedSlider.setFocusable(false);
        jSpeedSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSpeedSliderMouseDragged(evt);
            }
        });

        jHelpButton.setText("Help");
        jHelpButton.setFocusable(false);
        jHelpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHelpButtonMouseClicked(evt);
            }
        });

        jStopButton.setText("Stop");
        jStopButton.setFocusable(false);
        jStopButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jStopButtonMouseClicked(evt);
            }
        });

        jEraserRadioButton.setText("Eraser");
        jEraserRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEraserRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTopPanelLayout = new javax.swing.GroupLayout(jTopPanel);
        jTopPanel.setLayout(jTopPanelLayout);
        jTopPanelLayout.setHorizontalGroup(
            jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTopPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jHelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSolveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSliderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpeedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jStopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jEraserRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jTopPanelLayout.setVerticalGroup(
            jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jStopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jEraserRadioButton))
                    .addGroup(jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jHelpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSolveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSliderLabel)
                        .addComponent(jSpeedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(554, 554, 554))
        );

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(860, 530));

        jAlgoPanel.setBackground(new java.awt.Color(204, 204, 204));
        jAlgoPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jAlgoPanel.setForeground(new java.awt.Color(204, 255, 255));
        jAlgoPanel.setPreferredSize(new java.awt.Dimension(350, 400));

        jDijkstraButton.setText("Dijkstra");
        jDijkstraButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDijkstraButtonMouseClicked(evt);
            }
        });

        jAStarButton.setText("A-Star");
        jAStarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAStarButtonMouseClicked(evt);
            }
        });
        jAStarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAStarButtonActionPerformed(evt);
            }
        });

        jDFSButton.setText("DFS");
        jDFSButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDFSButtonMouseClicked(evt);
            }
        });

        jBFSButton.setText("BFS");
        jBFSButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBFSButtonMouseClicked(evt);
            }
        });

        jGreedyButton.setText("Greedy Best First");
        jGreedyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGreedyButtonMouseClicked(evt);
            }
        });

        jBidirectionalButton.setText("Bidirectional");
        jBidirectionalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBidirectionalButtonMouseClicked(evt);
            }
        });
        jBidirectionalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBidirectionalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jAlgoPanelLayout = new javax.swing.GroupLayout(jAlgoPanel);
        jAlgoPanel.setLayout(jAlgoPanelLayout);
        jAlgoPanelLayout.setHorizontalGroup(
            jAlgoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAlgoPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jAlgoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jAStarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDijkstraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDFSButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBFSButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jGreedyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jBidirectionalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jAlgoPanelLayout.setVerticalGroup(
            jAlgoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAlgoPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jDijkstraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jAStarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDFSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBFSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jGreedyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBidirectionalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jMainPanel.setPreferredSize(new java.awt.Dimension(860, 530));
        jMainPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jMainPanelMouseDragged(evt);
            }
        });
        jMainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMainPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(jAlgoPanel, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.setLayer(jMainPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(250, 250, 250)
                    .addComponent(jAlgoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(192, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jAlgoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(530, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 70, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSolveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSolveButtonMouseClicked
        if (!solving) {
            
            jAlgoPanel.setVisible(true);
            System.out.println("Hello from solve");
            this.pack();
            jAlgoPanel.requestFocusInWindow();
        }
        
    }//GEN-LAST:event_jSolveButtonMouseClicked

    private void jHelpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHelpButtonMouseClicked
        
        JOptionPane.showMessageDialog(this,
                new String[] {
                    "You are presented a rectangular grid of cells.",
                    " ",
                    "Step 1:",
                    "  Click on any cell to select the start and ending positions.",
                    " ",
                    "Step 2:",
                    "  Click and drag your mouse on any cell to create walls.",
                    " ",
                    "Step 3:",
                    "  Click on the 'Start' button and select any of the given algorithms.",
                    " ",
                    "Step 4:",
                    "  You may click on the 'Stop' button to stop the execution",
                    "at any point in time.",
                    " ",
                    "Step 5:",
                    " Use the slider at the top to adjust the speed of the visualisation."
                },
                "Help for Path Finder", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jHelpButtonMouseClicked

    private void jSpeedSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpeedSliderMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpeedSliderMouseDragged

    private void jStopButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStopButtonMouseClicked
        // TODO add your handling code here:
        solving = false;
    }//GEN-LAST:event_jStopButtonMouseClicked

    private void jAStarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAStarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAStarButtonActionPerformed

    private void jBidirectionalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBidirectionalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBidirectionalButtonActionPerformed

    private void jDijkstraButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDijkstraButtonMouseClicked
        // TODO add your handling code here:
        jAlgoPanel.setVisible(false);
        solving = true; // Keep track of the fact that solving has begun.
    }//GEN-LAST:event_jDijkstraButtonMouseClicked

    private void jDFSButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDFSButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jDFSButtonMouseClicked

    private void jBFSButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFSButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFSButtonMouseClicked

    private void jGreedyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGreedyButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jGreedyButtonMouseClicked

    private void jAStarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAStarButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jAStarButtonMouseClicked

    private void jBidirectionalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBidirectionalButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBidirectionalButtonMouseClicked

    private void jMainPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMainPanelMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==0) {
            return;
        }
        final Cell cell = gridPanel.mouseToCell(evt);
        System.out.println(String.format("Cell coord: %d, %d", cell.getRow(), cell.getCol()));
        if (cell == null) {
            System.out.println("null cell clicke");
            return;
        }
        
        if (cell.isNormal() && cellTypeCounter == 0) {
            System.out.println(String.format("Cell normal: %b", cell.isNormal()));
            cell.setStatus(1); //i.e status START = 1 
            gridPanel.setStart(cell);
            cellTypeCounter = 1;
            System.out.println(String.format("Cell start: %b", cell.isStart()));
        }
        else if (cell.isStart() && eraser) {
            System.out.println(String.format("Cell start: %b", cell.isStart()));
            cell.setStatus(0); // i.e. status NORMAL = 0
            gridPanel.setStart(null);
            cellTypeCounter = 0;
            System.out.println(String.format("Cell normal: %b", cell.isNormal()));
        }
        else if (cell.isNormal() && cellTypeCounter == 1) {
            cell.setStatus(2); // i.e status END = 2;
            gridPanel.setEnd(cell);
            cellTypeCounter = 2;
        }
        else if (cell.isEnd() && eraser) {
            cell.setStatus(0); // i.e. status NORMAL = 0
            gridPanel.setEnd(null);
            cellTypeCounter = 1;
        }
        else if (cell.isNormal() && cellTypeCounter ==2 && !eraser) {
            cell.setStatus(-1); // i.e status WALL = -1;
            gridPanel.setWalls(cell);
            cellTypeCounter =2;
        }
        else if (cell.isWall() && cellTypeCounter ==2 && eraser) {
            cell.setStatus(0); // i.e status NORMAL = 0;
            gridPanel.removeWalls(cell);
            cellTypeCounter =2;
        }
        
        jMainPanel.invalidate();
        repaint();
        jMainPanel.requestFocusInWindow();
    }//GEN-LAST:event_jMainPanelMouseClicked

    private void jMainPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMainPanelMouseDragged
        // TODO add your handling code here:
        
        final Cell cell = gridPanel.mouseToCell(evt);
        System.out.println(String.format("Cell coord: %d, %d", cell.getRow(), cell.getCol()));
        if (cell == null) {
            System.out.println("null cell clicke");
            return;
        }
        if (cell.isNormal() && cellTypeCounter ==2 && !eraser) {
            cell.setStatus(-1); // i.e status WALL = -1;
            gridPanel.setWalls(cell);
            cellTypeCounter =2;
        }
        else if (cell.isWall() && cellTypeCounter ==2 && eraser ) {
            cell.setStatus(0); // i.e status NORMAL = 0;
            gridPanel.removeWalls(cell);
            cellTypeCounter =2;
        }
        jMainPanel.invalidate();
        repaint();
        jMainPanel.requestFocusInWindow();
    }//GEN-LAST:event_jMainPanelMouseDragged

    private void jEraserRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEraserRadioButtonActionPerformed
        // TODO add your handling code here:
        if (eraser) {
            eraser = false;
        } else {
            eraser = true;
        }
    }//GEN-LAST:event_jEraserRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAStarButton;
    private java.awt.Panel jAlgoPanel;
    private javax.swing.JButton jBFSButton;
    private javax.swing.JButton jBidirectionalButton;
    private javax.swing.JButton jDFSButton;
    private javax.swing.JButton jDijkstraButton;
    private javax.swing.JRadioButton jEraserRadioButton;
    private javax.swing.JButton jGreedyButton;
    private javax.swing.JButton jHelpButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private gui.GridPanel jMainPanel;
    private javax.swing.JLabel jSliderLabel;
    private javax.swing.JButton jSolveButton;
    private javax.swing.JSlider jSpeedSlider;
    private javax.swing.JButton jStopButton;
    private javax.swing.JPanel jTopPanel;
    // End of variables declaration//GEN-END:variables
    private final GridPanel gridPanel;
    private boolean solving=false;
    private boolean eraser = false;
    private int cellTypeCounter=0; // used to keep track of the type of cells that have been selected
    // 1 for start cell, 2 for stop cell, >2 for wall cell
    
   
}
